spring.application.name=SpringSecurity
spring.security.user.name=admin
spring.security.user.password=pass

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test

spring.app.jwtSecretKey=SecretKey101@meow
spring.app.jwtExpirationMs=500000000000